// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// D1_2nd
double D1_2nd(double n, double f1, double f2, double rho);
RcppExport SEXP _iNEXT_scaling_D1_2nd(SEXP nSEXP, SEXP f1SEXP, SEXP f2SEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type f1(f1SEXP);
    Rcpp::traits::input_parameter< double >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(D1_2nd(n, f1, f2, rho));
    return rcpp_result_gen;
END_RCPP
}
// Dq_2nd
double Dq_2nd(double n, double f1, double A, double q, double rho);
RcppExport SEXP _iNEXT_scaling_Dq_2nd(SEXP nSEXP, SEXP f1SEXP, SEXP ASEXP, SEXP qSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type f1(f1SEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(Dq_2nd(n, f1, A, q, rho));
    return rcpp_result_gen;
END_RCPP
}
// Dq
NumericVector Dq(NumericMatrix ifi, int n, NumericVector qs, double f1, double A, double rho);
RcppExport SEXP _iNEXT_scaling_Dq(SEXP ifiSEXP, SEXP nSEXP, SEXP qsSEXP, SEXP f1SEXP, SEXP ASEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ifi(ifiSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type qs(qsSEXP);
    Rcpp::traits::input_parameter< double >::type f1(f1SEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(Dq(ifi, n, qs, f1, A, rho));
    return rcpp_result_gen;
END_RCPP
}
// qDFUN
NumericVector qDFUN(NumericVector q, NumericVector Xi, const int n);
RcppExport SEXP _iNEXT_scaling_qDFUN(SEXP qSEXP, SEXP XiSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xi(XiSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(qDFUN(q, Xi, n));
    return rcpp_result_gen;
END_RCPP
}
// qD_MLE
NumericVector qD_MLE(NumericVector q, NumericVector ai);
RcppExport SEXP _iNEXT_scaling_qD_MLE(SEXP qSEXP, SEXP aiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ai(aiSEXP);
    rcpp_result_gen = Rcpp::wrap(qD_MLE(q, ai));
    return rcpp_result_gen;
END_RCPP
}
// RD
NumericVector RD(NumericMatrix x, int n, double m, NumericVector q);
RcppExport SEXP _iNEXT_scaling_RD(SEXP xSEXP, SEXP nSEXP, SEXP mSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(RD(x, n, m, q));
    return rcpp_result_gen;
END_RCPP
}
// RD_inc
NumericVector RD_inc(NumericMatrix y, int nT, double t_, NumericVector q);
RcppExport SEXP _iNEXT_scaling_RD_inc(SEXP ySEXP, SEXP nTSEXP, SEXP t_SEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type nT(nTSEXP);
    Rcpp::traits::input_parameter< double >::type t_(t_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(RD_inc(y, nT, t_, q));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_iNEXT_scaling_D1_2nd", (DL_FUNC) &_iNEXT_scaling_D1_2nd, 4},
    {"_iNEXT_scaling_Dq_2nd", (DL_FUNC) &_iNEXT_scaling_Dq_2nd, 5},
    {"_iNEXT_scaling_Dq", (DL_FUNC) &_iNEXT_scaling_Dq, 6},
    {"_iNEXT_scaling_qDFUN", (DL_FUNC) &_iNEXT_scaling_qDFUN, 3},
    {"_iNEXT_scaling_qD_MLE", (DL_FUNC) &_iNEXT_scaling_qD_MLE, 2},
    {"_iNEXT_scaling_RD", (DL_FUNC) &_iNEXT_scaling_RD, 4},
    {"_iNEXT_scaling_RD_inc", (DL_FUNC) &_iNEXT_scaling_RD_inc, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_iNEXT_scaling(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
